"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
require("./assets/base.css");
require("./assets/front.css");
require("./assets/layout.css");
require("./assets/reset.css");
require("./assets/setting-market.css");
var vue_1 = require("vue");
var App_vue_1 = require("./App.vue");
(0, vue_1.createApp)(App_vue_1.default).mount('#app');
